blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :users

  resources :articles do
    resources :comments
  end
  
  root 'welcome#index'

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true,
					length: { minimum: 5 },
					uniqueness: true

	validates :text, presence: true, uniqueness: true

	belongs_to :user

	has_many :comments, dependent: :destroy

end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :commenter, presence: true
	validates :body, presence: true
	belongs_to :article, :user
end

blog/app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	validates :username,
		presence: true,
		uniqueness: true,
		length: {
			minimum: 4,
			maximum: 50,
		}
	validates :password_digest,
		presence: true,
		length: {
			minimum: 6,
			maximum: 255,
		}
	validates :email,
		uniqueness: true,
		presence: true
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "bmo", password: "qazwert4",
		except: [:index, :show]

	def index
		@articles = Article.all
	end

	def edit
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		
		redirect_to articles_path
	end

	private
	def article_params
		params.require(:article).permit(:title, :text)
	end

end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)

		redirect_to @article
	end


	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

blog/app/controllers/index_controller.rb
class IndexController < ApplicationController
end

blog/app/controllers/user_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
	end

	def create
	end

end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to User.all
		else
			render 'new'
		end
	end

	private
		def user_params
			params.require(:user).permit(:username, :email, :password)
		end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/index_helper.rb
module IndexHelper
end

blog/app/helpers/user_helper.rb
module UserHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
	<% if @article.errors.any? %>
		<div id ="error_explanation">
			<h2>
				<%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
 			</h2>
 			<ul>
 				<% @article.errors.full_messages.each do |msg| %>
 				<li><%= msg %></li>
 				<% end %>
 			</ul>
 		</div>
 	<% end %>
<% end %>

blog/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Back to All Posts', articles_path %>

blog/app/views/articles/index.html.erb
<h1>Listings Articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
	<tr>
		<th>Id</th>
		<th>Title</th>
		<th>text</th>
		<th>Posted</th>
		<th colspan="3"><th>
	</tr>

	<% @articles.each do |article| %>
	<tr>
		<td><%= article.id %></td>
		<td><%= article.title %></td>
		<td><%= article.text %></td>
		<td><%= article.created_at.to_date %></td>
		<td><%= link_to 'Show', article %></td>
		<td><%= link_to 'Edit', edit_article_path(article) %></td>
		<td><%= link_to 'Destroy', article_path(article),
				method: :delete,
				data: {confirm: 'Are you sure?'} %></td>
	</tr>
	<% end %>
</table>

blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
	<% if @article.errors.any? %>
		<div id ="error_explanation">
			<h2>
				<%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
 			</h2>
 			<ul>
 				<% @article.errors.full_messages.each do |msg| %>
 				<li><%= msg %></li>
 				<% end %>
 			</ul>
 		</div>
 	<% end %>
<% end %>

<%= link_to 'Back to All Posts', controller: 'articles' %>

blog/app/views/articles/show.html.erb
<h1>This is totally an article!: <%= @article.id %></h1>
<p>
	<%= @article.title %>
</p>

<p>
	<%= @article.text %>
</p>


<h2>Comments</h2>
<%= render @article.comments %>

<h2> Add a Comment</h2>
<%= render 'comments/form' %>

<%= link_to 'EDIT', edit_article_path(@article) %> | 
<%= link_to 'BACK', articles_path %>

blog/app/views/comments/_comment.html.erb
<p>
	<strong>Commenter:</strong>
	<%= comment.commenter %>
</p>

<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>

blog/app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %><br>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<%= f.label :username %><br>
	<%= f.text_field :username %><br>
	<br>
	<%= f.label :email %><br>
	<%= f.text_field :email %><br>
	<br>
	<%= f.label :password %><br>
	<%= f.text_field :password %><br>

	<%= f.submit %>
	<% if @user.errors.any? %>
		<div id ="error_explanation">
			<h2>
				<%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
 			</h2>
 			<ul>
 				<% @user.errors.full_messages.each do |msg| %>
 				<li><%= msg %></li>
 				<% end %>
 			</ul>
 		</div>
 	<% end %>
<% end %>

blog/app/views/users/index.html.erb
<h1>USERS!</h1>
<%= link_to 'New User', new_user_path %>
<table>
	<tr>
		<th>ID</th>
		<th>Username</th>
		<th>Email</th>
	</tr>

	<% @users.each do |user| %>
		<tr>
			<td><%= user.id %></td>
			<td><%= user.username %></td>
			<td><%= user.email %></td>
		</tr>
	<% end %>
</table>

blog/app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form' %>

blog/app/views/welcome/index.html.erb
<h1>Hello From Rails!</h1>

<%= link_to 'My Blog!', :articles %>
<%= link_to 'Users', :users %>